create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text not null unique,
  phone text,
  role text not null default 'customer',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.login_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  full_name text,
  email text not null,
  phone text,
  role text,
  user_details jsonb,
  ip_address text,
  user_agent text,
  access_token text,
  logged_in_at timestamptz not null default now(),
  logged_out_at timestamptz,
  is_active boolean not null default true
);

alter table public.profiles enable row level security;
alter table public.login_logs enable row level security;

create or replace function public.handle_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop policy if exists "Profiles are viewable by owner" on public.profiles;
create policy "Profiles are viewable by owner"
on public.profiles
for select
using (auth.uid() = id);

drop policy if exists "Profiles can be inserted by owner" on public.profiles;
create policy "Profiles can be inserted by owner"
on public.profiles
for insert
with check (auth.uid() = id);

drop policy if exists "Profiles can be updated by owner" on public.profiles;
create policy "Profiles can be updated by owner"
on public.profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Login logs are viewable by owner" on public.login_logs;
create policy "Login logs are viewable by owner"
on public.login_logs
for select
using (auth.uid() = user_id);

drop policy if exists "Login logs can be inserted by owner" on public.login_logs;
create policy "Login logs can be inserted by owner"
on public.login_logs
for insert
with check (auth.uid() = user_id);

drop policy if exists "Login logs can be updated by owner" on public.login_logs;
create policy "Login logs can be updated by owner"
on public.login_logs
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row
execute function public.handle_updated_at();


create table if not exists public.appointments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  service text not null,
  stylist text not null,
  date date not null,
  time text not null,
  price text not null,
  status text not null default 'Confirmed',
  icon text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.appointments enable row level security;

drop policy if exists "Appointments are viewable by owner" on public.appointments;
create policy "Appointments are viewable by owner"
on public.appointments
for select
using (auth.uid() = user_id);

drop policy if exists "Appointments can be inserted by owner" on public.appointments;
create policy "Appointments can be inserted by owner"
on public.appointments
for insert
with check (auth.uid() = user_id);

drop policy if exists "Appointments can be updated by owner" on public.appointments;
create policy "Appointments can be updated by owner"
on public.appointments
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Appointments can be deleted by owner" on public.appointments;
create policy "Appointments can be deleted by owner"
on public.appointments
for delete
using (auth.uid() = user_id);

drop trigger if exists appointments_set_updated_at on public.appointments;
create trigger appointments_set_updated_at
before update on public.appointments
for each row
execute function public.handle_updated_at();
