create table users (
    id bigint generated by default as identity primary key,
    name text not null,
    email text unique not null,
    password text not null,
    created_at timestamp default now()
);

